steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/flaskapp:$SHORT_SHA','.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/flaskapp:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'set'
    - 'image'
    - 'deployment/flaskapp'
    - 'flaskapp=gcr.io/$PROJECT_ID/flaskapp:$SHORT_SHA'
    - '--record'
    - '--namespace=prod'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-2'
images: ['gcr.io/cloud-builders/kubectl']
