steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/flaskapp','.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/flaskapp']
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=gke.yaml
    - --namespace=prod 
    - --cluster=cluster-2

