apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: gcr.io/careful-journey-395914/flaskapp:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
