apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: gcr.io/careful-journey-395914/flaskapp:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
            
apiVersion: apps/v1
kind: Service
metadata:
  name: flaskappservice
  namespace: prod
  labels:
    app.kubernetes.io/managed-by:"gcp-cloud-build-deploy"
spec:
 ports:
 - protocol: "TCP"
   port: 80
   targetPort: 5000
 selector:
   app: flaskapp
 type: "LoadBalancer"


